### ISSUE TITLE
`pod try` doesn't work

### ISSUE THREAD

**Issue by aaronbrethorst** [Rounded/ROSwipenger#3]
`pod try ROSwipenger` creates a workspace that fails to build.

**Comment by heatherSnepenger** [comment]
hmmm. I'm not sure what that's about. I'll look into it.

**Comment by heatherSnepenger** [comment]
The Podfile.lock had wrong version in it. The pod has been updated, and should now work properly with `pod try'

**Comment by aaronbrethorst** [comment]
that did it, thanks!
